export let menuData = [
    {
        "title1" : "English Breakfast",
        "desc1" : "smoked bacon, sausage, tomato, mushrooms, black pudding, baked beans, eggs",
        "price1" : "£12",
        "title2" : "Avocado Toast",
        "desc1" : "poached egg, avocado, onion, tomatoes, bread",
        "price2" : "£8",
        "title3" : "Burrito",
        "desc3" : "tortilla, egg, cheese, potatoes, pork meat",
        "price3" : "£11",
    },
    {
        "title1" : "Caesar Salad",
        "desc1" : "chicken breast, romaine lettuce, croutons, parmesan",
        "price1" : "£15",
        "title2" : "Spaghetti Carbonara",
        "desc1" : "spaghetti, pancetta, garlic, eggs, parmesan, pepper",
        "price2" : "£14",
        "title3" : "Pizza",
        "desc3" : "chorizo, italian salami, tomatoes, mushrooms, olives",
        "price3" : "£12",
    },
    {
        "title1" : "Spicy Beef",
        "desc1" : "spicy beef, potatoes, carrots, cheese sauce, spices",
        "price1" : "£17",
        "title2" : "Spaghetti Bolognese",
        "desc1" : "onion, carrot, celery, minced meat, spaghetti, parmesan",
        "price2" : "£15",
        "title3" : "Chickpea Curry",
        "desc3" : "onion, chickpea, garlic, mushrooms, tomatoes, spices",
        "price3" : "£12",
    },
    {
        "title1" : "Lemon Cake",
        "desc1" : "flour, sugar, baking powder, lemon",
        "price1" : "£9",
        "title2" : "Cinnamon Rolls",
        "desc1" : "flour, salt, sugar, cinnamon, yeast, sour cream, milk",
        "price2" : "£11",
        "title3" : "Vegan Pancakes",
        "desc3" : "flour, sugar, baking powder, soya milk, blueberries",
        "price3" : "£8",
    },
]